// Cypher — DMV Defense Tech Intelligence Platform
// All data is representative/illustrative for demonstration purposes only

window.CYPHER_DATA = {

  nodes: [
    // ── GOVERNMENT AGENCIES ──────────────────────────────────────────
    { id:'darpa', type:'government', name:'DARPA', size:'xl', tags:['AI','autonomy','biotech','space','cyber'], description:'Defense Advanced Research Projects Agency. Primary driver of breakthrough military technology. Offices in Arlington, VA.', activity:[{date:'2026-03-15',type:'contract',text:'Awarded $34M SBIR Phase II to Anduril for autonomous swarm systems'},{date:'2026-03-10',type:'contract',text:'Issued BAA for AI-assisted intelligence analysis — $200M ceiling'},{date:'2026-02-28',type:'hiring',text:'Posted 12 PM positions across AI and biodefense tracks'}] },
    { id:'dod', type:'government', name:'Dept. of Defense', size:'xl', tags:['defense','cyber','AI','space'], description:'Pentagon headquarters. Manages all U.S. military branches and defense procurement. 900K civilian employees.', activity:[{date:'2026-03-14',type:'contract',text:'$2.1B JEDI cloud successor award to Microsoft and Google Cloud'},{date:'2026-03-05',type:'hiring',text:'Opened 300+ positions under OUSD(R&E) AI taskforce expansion'}] },
    { id:'cia', type:'government', name:'CIA / Intel Community', size:'lg', tags:['cyber','AI','dual-use'], description:'Central Intelligence Agency and broader IC. Langley, VA campus. In-Q-Tel portfolio primary funding arm.', activity:[{date:'2026-03-12',type:'funding',text:'In-Q-Tel seed investment in DC-based ML inference startup'},{date:'2026-02-20',type:'hiring',text:'Recruiting data scientists with TS/SCI for NLP targeting systems'}] },
    { id:'nsa', type:'government', name:'NSA / Cybersecurity Div.', size:'lg', tags:['cyber','AI','signals'], description:'National Security Agency, Fort Meade, MD. CISA coordination hub. Largest employer of mathematicians in the U.S.', activity:[{date:'2026-03-16',type:'contract',text:'Awarded $78M cyber modernization contract to Booz Allen Hamilton'},{date:'2026-03-08',type:'hiring',text:'Surge hiring for quantum-resistant cryptography researchers'}] },
    { id:'dhs', type:'government', name:'DHS / CISA', size:'md', tags:['cyber','critical-infra'], description:'Department of Homeland Security and Cybersecurity Infrastructure Security Agency.', activity:[{date:'2026-03-11',type:'contract',text:'$45M contract to Mandiant for critical infrastructure threat intel'}] },
    { id:'dod_diu', type:'government', name:'DIU', size:'md', tags:['AI','dual-use','cyber','space'], description:'Defense Innovation Unit — commercial technology accelerator for the Pentagon. Bridges Silicon Valley and Washington.', activity:[{date:'2026-03-17',type:'contract',text:'OTA award to Shield AI — autonomous flight systems $125M'},{date:'2026-03-09',type:'funding',text:'DIU portfolio review: 14 active contracts in AI/ML space'}] },
    { id:'nga', type:'government', name:'NGA', size:'md', tags:['AI','space','intelligence'], description:'National Geospatial-Intelligence Agency. Maps, imagery, and geospatial intelligence for national security decisions.', activity:[{date:'2026-03-13',type:'contract',text:'$22M contract renewal with Primer AI for geospatial NLP'},{date:'2026-03-04',type:'hiring',text:'NGA Moonshot: 50 ML/CV engineers under new AI initiative'}] },
    { id:'socom', type:'government', name:'USSOCOM', size:'md', tags:['autonomy','AI','defense'], description:'United States Special Operations Command. Forward-deploying advanced technology to tip-of-spear operators.', activity:[{date:'2026-03-16',type:'contract',text:'$180M SOCOM AI-enabled ISR platform awarded to Palantir'},{date:'2026-03-10',type:'hiring',text:'SOFWERX open challenge: $2M for counter-UAS detection system'}] },
    { id:'afrl', type:'government', name:'AFRL', size:'md', tags:['AI','space','autonomy','defense'], description:'Air Force Research Laboratory. Executes the Air Force science and technology program. Key node in DC-area defense innovation.', activity:[{date:'2026-03-14',type:'contract',text:'$67M IDIQ to Rebellion Defense for AI targeting software'},{date:'2026-03-06',type:'research',text:'Published autonomy roadmap: AI co-pilot for contested airspace'}] },
    { id:'dtra', type:'government', name:'DTRA', size:'sm', tags:['biotech','defense','cyber'], description:'Defense Threat Reduction Agency. Reduces chemical, biological, radiological, nuclear and high-yield explosive threats.', activity:[{date:'2026-03-09',type:'contract',text:'$14M biosurveillance AI contract awarded to DC-based startup'}] },

    // ── VENTURE CAPITAL ───────────────────────────────────────────────
    { id:'iqt', type:'vc', name:'In-Q-Tel', size:'xl', tags:['dual-use','cyber','AI','biotech'], description:'Strategic investment arm of the U.S. Intelligence Community. Funds technology with national security applications. ~$500M deployed.', activity:[{date:'2026-03-15',type:'funding',text:'Led $18M Series A in Epirus — directed energy startup'},{date:'2026-03-01',type:'funding',text:'Seed investment in Arlington-based satellite imagery AI company'}] },
    { id:'paladin', type:'vc', name:'Paladin Capital Group', size:'lg', tags:['cyber','dual-use','AI','critical-infra'], description:'Global multi-stage investor focused on national security and cyber. Pentagon Row, Washington DC. $2.5B AUM.', activity:[{date:'2026-03-14',type:'funding',text:'Growth equity round — $90M into zero-trust network startup'},{date:'2026-03-07',type:'funding',text:'New $500M fund close: National Security Technology Fund III'}] },
    { id:'lux', type:'vc', name:'Lux Capital DC', size:'md', tags:['AI','space','biotech','dual-use'], description:'Science and deep tech VC. $5B AUM. DC office covers government partnerships and dual-use portfolio.', activity:[{date:'2026-03-10',type:'funding',text:'New $150M fund close focused on dual-use AI applications'}] },
    { id:'avp', type:'vc', name:'AV8 Ventures', size:'md', tags:['AI','defense','cyber'], description:'Deep tech and dual-use venture firm. DC presence with portfolio spanning defense AI, space, and quantum.', activity:[{date:'2026-03-13',type:'funding',text:'Co-led $55M Series B in autonomous maritime defense startup'}] },
    { id:'osage', type:'vc', name:'Osage Venture Partners', size:'sm', tags:['cyber','defense','AI'], description:'Mid-Atlantic focused early-stage VC. Strong ties to DoD contractor ecosystem and IC community.', activity:[{date:'2026-03-06',type:'funding',text:'Seed round in DC-area quantum sensing startup — $6M'}] },
    { id:'a16z_def', type:'vc', name:'a16z American Dynamism', size:'lg', tags:['defense','AI','autonomy','space'], description:'Andreessen Horowitz defense and national security practice. $600M fund targeting American industrial base.', activity:[{date:'2026-03-12',type:'funding',text:'Led $200M Series D in autonomous undersea vehicle startup'},{date:'2026-03-05',type:'funding',text:'Co-invested in two SBIR Phase II defense AI companies'}] },
    { id:'shield_cap', type:'vc', name:'Shield Capital', size:'md', tags:['defense','cyber','AI'], description:'Defense-focused early-stage VC led by former DoD and IC officials. Thesis: commercial tech for national security.', activity:[{date:'2026-03-11',type:'funding',text:'Announced $185M Fund II — focus on AI, cyber, and dual-use'},{date:'2026-03-03',type:'funding',text:'Seed investment in counter-drone AI startup out of MIT LL'}] },
    { id:'sq1', type:'vc', name:'Silicon Valley Bank (DC)', size:'sm', tags:['defense','AI','cyber'], description:'SVB defense tech banking arm. Provides debt and equity to defense tech ecosystem in DC metro.', activity:[{date:'2026-03-09',type:'funding',text:'$40M venture debt facility to Anduril for R&D expansion'}] },
    { id:'primer_vc', type:'vc', name:'Primavera Capital', size:'sm', tags:['AI','dual-use','space'], description:'Cross-border tech investor with defense AI focus. Growing DC presence as DoD AI procurement expands.', activity:[{date:'2026-03-08',type:'funding',text:'$12M co-investment in satellite constellation AI startup'}] },

    // ── STARTUPS ──────────────────────────────────────────────────────
    { id:'anduril', type:'startup', name:'Anduril Industries', size:'xl', tags:['autonomy','AI','defense','dual-use'], description:'Defense technology company building autonomous systems, border security, and AI-powered C2 platforms. Founded by Palmer Luckey. $2.3B raised.', activity:[{date:'2026-03-17',type:'contract',text:'$2B DoD contract for integrated defense infrastructure systems'},{date:'2026-03-12',type:'hiring',text:'45 roles opened in Arlington — ML engineers, systems architects'},{date:'2026-02-28',type:'contract',text:'DARPA award for autonomous swarm coordination — $34M'}] },
    { id:'shield_ai', type:'startup', name:'Shield AI', size:'xl', tags:['autonomy','AI','defense'], description:'AI pilot technology for military aircraft. Hivemind AI enables autonomous flight without GPS or communications. $850M raised.', activity:[{date:'2026-03-16',type:'contract',text:'OTA from DIU — autonomous flight systems $125M'},{date:'2026-03-07',type:'hiring',text:'20 software engineers hired from ex-Google and Uber teams'}] },
    { id:'rebellion_def', type:'startup', name:'Rebellion Defense', size:'lg', tags:['AI','cyber','defense','dual-use'], description:'AI-powered warfighting software. Builds intelligence fusion and cyber defense platforms for DoD and Five Eyes. $150M raised.', activity:[{date:'2026-03-14',type:'contract',text:'Air Force contract for AI targeting assistance — $67M IDIQ'},{date:'2026-03-03',type:'hiring',text:'Recruiting ex-NSA signals intelligence experts — 15 openings'}] },
    { id:'primer_ai', type:'startup', name:'Primer AI', size:'md', tags:['AI','NLP','intelligence'], description:'Natural language AI for national security and intelligence. Automates reading and analysis of vast document corpora. $126M raised.', activity:[{date:'2026-03-10',type:'contract',text:'NGA contract renewal for geospatial intelligence AI — $22M'},{date:'2026-02-25',type:'hiring',text:'Hiring computational linguists with active clearance'}] },
    { id:'sievert', type:'startup', name:'Sievert Labs', size:'sm', tags:['cyber','zero-trust','AI'], description:'DC-native zero-trust network security startup. Built by ex-NSA operators. Focuses on critical infrastructure protection. $12M raised.', activity:[{date:'2026-03-15',type:'funding',text:'Closed $12M seed from Paladin Capital + In-Q-Tel'},{date:'2026-03-11',type:'hiring',text:'First hire: VP of Engineering from Palo Alto Networks'}] },
    { id:'vannevar', type:'startup', name:'Vannevar Labs', size:'md', tags:['AI','intelligence','dual-use'], description:'AI for national security decision-making. Provides intelligence analysts with open-source and classified data fusion tools. $92M raised.', activity:[{date:'2026-03-09',type:'contract',text:'DIA contract — AI intelligence fusion platform — $41M'},{date:'2026-03-02',type:'hiring',text:'Expanding DC team — 8 cleared ML engineer roles posted'}] },
    { id:'aurora_insight', type:'startup', name:'Aurora Insight', size:'sm', tags:['space','signals','AI'], description:'Spectrum intelligence platform. Maps and analyzes RF signals globally using cubesat constellation. $30M raised.', activity:[{date:'2026-03-13',type:'funding',text:'Series A from Lux Capital — $30M for constellation expansion'}] },
    { id:'skydio', type:'startup', name:'Skydio (DoD)', size:'md', tags:['autonomy','AI','defense','ISR'], description:'American autonomous drone company. Defense programs office in Arlington manages DoD contracts and SBIR activity. $340M raised.', activity:[{date:'2026-03-16',type:'contract',text:'Army Blue UAS program award — $20M initial tranche'}] },
    { id:'envision_x', type:'startup', name:'EnvisionX', size:'sm', tags:['AI','cyber','defense'], description:'Edge AI inference platform for contested environments. Founded by ex-Palantir and ex-Booz Allen engineers. $8M raised.', activity:[{date:'2026-03-08',type:'funding',text:'Seed round — $8M from AV8 Ventures + Osage'},{date:'2026-03-04',type:'hiring',text:'Hiring firmware engineers and RF systems specialists'}] },
    { id:'palantir', type:'startup', name:'Palantir (DC Office)', size:'xl', tags:['AI','intelligence','defense','dual-use'], description:'Data analytics platform used by DoD, IC, and law enforcement. DC office is primary government sales and delivery hub. NYSE: PLTR.', activity:[{date:'2026-03-17',type:'contract',text:'SOCOM $180M AI-enabled ISR platform contract'},{date:'2026-03-14',type:'contract',text:'Army AIP Phase II: $400M AI integration across brigade combat teams'},{date:'2026-03-08',type:'hiring',text:'Hiring 30 Forward Deployed Engineers in Arlington, VA'}] },
    { id:'booz_allen', type:'startup', name:'Booz Allen Hamilton', size:'xl', tags:['cyber','AI','defense','intelligence'], description:'Management and technology consulting firm. Largest single contractor to the U.S. Intelligence Community. $10B revenue. NYSE: BAH.', activity:[{date:'2026-03-16',type:'contract',text:'NSA $78M cyber modernization contract awarded'},{date:'2026-03-11',type:'contract',text:'DHS Cyber defense modernization — $120M recompete win'},{date:'2026-03-06',type:'hiring',text:'400+ cleared positions posted across DC metro'}] },
    { id:'leidos', type:'startup', name:'Leidos', size:'lg', tags:['defense','AI','space','cyber'], description:'Defense, intelligence, and health solutions contractor. One of the largest U.S. defense primes with strong DC-area presence. NYSE: LDOS.', activity:[{date:'2026-03-15',type:'contract',text:'$1.4B Air Force IT modernization contract awarded'},{date:'2026-03-09',type:'hiring',text:'Open call for 200 AI/ML engineers in Reston, VA'}] },
    { id:'epirus', type:'startup', name:'Epirus', size:'md', tags:['defense','autonomy','AI'], description:'Directed energy and high-power microwave startup. Leonidas counter-drone platform fielded with multiple U.S. services. $200M raised.', activity:[{date:'2026-03-15',type:'funding',text:'$18M Series A co-led by In-Q-Tel and Lux Capital'},{date:'2026-03-10',type:'contract',text:'Army fielding contract for Leonidas HPM system — $66M'}] },
    { id:'sarcos', type:'startup', name:'Sarcos Defense', size:'sm', tags:['autonomy','AI','defense'], description:'Robotic exoskeleton and unmanned ground vehicle company. Guardian XO and Guardian XT platforms for military logistics.', activity:[{date:'2026-03-12',type:'contract',text:'Army MANSCOUT award — robotic mule competition finalist $8M'},{date:'2026-03-05',type:'hiring',text:'Hiring mechatronics engineers for DC-area R&D hub'}] },
    { id:'hawkeye360', type:'startup', name:'HawkEye 360', size:'md', tags:['space','signals','AI','defense'], description:'RF signal intelligence from commercial satellite constellation. Detects, characterizes, and geolocates RF emissions globally.', activity:[{date:'2026-03-13',type:'contract',text:'NRO contract extension — $55M geospatial RF intelligence'},{date:'2026-03-07',type:'funding',text:'Series C close — $145M led by Shield Capital + a16z'}] },

    // ── UNIVERSITIES / RESEARCH LABS ──────────────────────────────────
    { id:'jhu_apl', type:'university', name:'JHU Applied Physics Lab', size:'xl', tags:['AI','space','cyber','autonomy','defense'], description:"Johns Hopkins University Applied Physics Laboratory. Largest university-affiliated R&D center in the U.S. DoD's largest FFRDC. $2.2B annual R&D.", activity:[{date:'2026-03-17',type:'research',text:'Published hypersonic vehicle guidance AI results in collab with DARPA'},{date:'2026-03-10',type:'contract',text:'New $340M Navy contract for missile defense systems research'},{date:'2026-03-05',type:'research',text:'NSF grant — quantum sensing for GPS-denied navigation — $18M'}] },
    { id:'umd', type:'university', name:'Univ. of Maryland', size:'lg', tags:['AI','cyber','quantum'], description:'Leading mid-Atlantic research university. Maryland Cybersecurity Center and ICS close to NSA/Fort Meade corridor.', activity:[{date:'2026-03-12',type:'research',text:'NSA-funded CyberCorps scholarship renewal — $5M over 3 years'},{date:'2026-03-06',type:'research',text:'New quantum computing center opens with NIST funding — $22M'}] },
    { id:'georgetown', type:'university', name:'Georgetown University', size:'md', tags:['AI','cyber','policy'], description:'Georgetown AI and national security research center. CSET (Center for Security and Emerging Technology) produces leading policy research.', activity:[{date:'2026-03-15',type:'research',text:'CSET report: "AI Chips and China Export Controls" — cited in Senate'},{date:'2026-03-08',type:'research',text:'New $3M MacArthur grant for biosecurity AI policy research'}] },
    { id:'gmu', type:'university', name:'George Mason Univ.', size:'md', tags:['AI','cyber','defense','autonomy'], description:'Northern Virginia tech research hub. Center for Secure Intelligent Systems. Close ties to DoD contractor corridor in Rosslyn/Tysons.', activity:[{date:'2026-03-11',type:'research',text:'DARPA-funded autonomy lab: new $12M award for swarm robotics'},{date:'2026-03-03',type:'research',text:'Published deep learning threat detection paper — 800+ citations'}] },
    { id:'nist', type:'university', name:'NIST', size:'lg', tags:['AI','cyber','quantum'], description:'Federal research laboratory. Leads AI safety frameworks, post-quantum cryptography standards, and cybersecurity guidelines.', activity:[{date:'2026-03-16',type:'research',text:'Released NIST AI RMF 2.0 — governs federal AI deployment standards'},{date:'2026-03-09',type:'research',text:'Post-quantum cryptography final standards publication'}] },
    { id:'mit_ll', type:'university', name:'MIT Lincoln Lab', size:'xl', tags:['AI','space','cyber','defense','autonomy'], description:'Federally funded R&D center operated by MIT. Develops advanced technology for national security. Key DARPA and DoD partner.', activity:[{date:'2026-03-14',type:'research',text:'Published autonomous air traffic deconfliction algorithm — DoD-funded'},{date:'2026-03-09',type:'contract',text:'DARPA OFFSET Phase III — autonomous swarm coordination $45M'},{date:'2026-03-03',type:'research',text:'Quantum networking testbed milestone: 500-node entanglement achieved'}] },
    { id:'rand', type:'university', name:'RAND Corporation', size:'md', tags:['AI','defense','policy','cyber'], description:'Research organization providing objective analysis and advice to government. Key influence on defense policy and AI governance frameworks.', activity:[{date:'2026-03-15',type:'research',text:'Published "AI Autonomy in Lethal Systems" — cited by SecDef staff'},{date:'2026-03-08',type:'research',text:'New $8M DoD contract for AI procurement policy research'}] },
    { id:'cna', type:'university', name:'CNA (Think Tank)', size:'sm', tags:['defense','AI','policy'], description:'Center for Naval Analyses. Operates the Navy FFRDC. Provides operations research and analysis to DoD and national security community.', activity:[{date:'2026-03-11',type:'research',text:'Report: Navy unmanned surface vessel fleet composition study — $6M'}] },

    // ── KEY OPERATORS / PEOPLE ────────────────────────────────────────
    { id:'person_lynch', type:'person', name:'Chris Lynch', size:'md', tags:['operator','ex-defense','founder'], description:'Former Director of Defense Digital Service (DDS). Led Pentagon tech modernization. Harvard MBA. Now CEO Rebellion Defense.', activity:[{date:'2026-03-15',type:'hiring',text:'Recruited 3 ex-NSA engineers to Rebellion Defense AI team'},{date:'2026-03-10',type:'contract',text:'Testified before SASC on AI systems procurement reform'}] },
    { id:'person_camarillo', type:'person', name:'Nicole Camarillo', size:'sm', tags:['operator','ex-government','founder'], description:'Former DoD cyber policy, NSC. Army Cyber veteran. Georgetown Law. Now Chief Strategy Officer at Rebellion Defense.', activity:[{date:'2026-03-12',type:'hiring',text:'Hired as CSO at Rebellion Defense following NSC departure'}] },
    { id:'person_gourley', type:'person', name:'Sean Gourley', size:'md', tags:['founder','AI','repeat-founder'], description:'PhD Physics Oxford. Rhodes Scholar. Co-founded Quid (acq. NetBase). Expert in mathematical conflict dynamics. Now CEO Primer AI.', activity:[{date:'2026-03-10',type:'contract',text:'Closed NGA contract renewal — Primer AI platform $22M'},{date:'2026-03-05',type:'funding',text:'Raised $45M Series C for Primer AI NLP expansion'}] },
    { id:'person_parks', type:'person', name:'Jenna Parks', size:'sm', tags:['founder','ex-palantir','AI'], description:'Ex-Palantir (6 years, Forward Deployed Engineer). Stanford CS. Embedded with SOCOM teams. Now CEO & Co-founder EnvisionX.', activity:[{date:'2026-03-08',type:'funding',text:'Closed $8M seed for EnvisionX — led by AV8 Ventures'}] },
    { id:'person_walsh', type:'person', name:'Morgan Walsh', size:'sm', tags:['founder','ex-nsa','cyber'], description:'Former NSA TAO operator (12 years). Yale CS. Led offensive cyber ops team. Now Founder & CEO Sievert Labs.', activity:[{date:'2026-03-15',type:'funding',text:'Closed Sievert Labs $12M seed — In-Q-Tel + Paladin Capital'}] },
    { id:'person_luckey', type:'person', name:'Palmer Luckey', size:'lg', tags:['founder','defense','AI','repeat-founder'], description:'Founder Anduril Industries. Former founder Oculus VR (acq. Facebook $2B). Pioneering autonomous defense systems. Forbes 30 Under 30.', activity:[{date:'2026-03-17',type:'contract',text:'Anduril wins $2B DoD integrated defense infrastructure contract'},{date:'2026-03-12',type:'hiring',text:'Opened 45 engineering roles in Arlington office'}] },
    { id:'person_shyu', type:'person', name:'Heidi Shyu (fmr.)', size:'md', tags:['operator','ex-defense','advisor'], description:'Former USD(R&E). First woman to hold that role. Now key advisor to multiple defense tech startups. Board member at Leidos and Shield AI.', activity:[{date:'2026-03-14',type:'hiring',text:'Joined Shield AI board of directors as independent director'},{date:'2026-03-05',type:'research',text:'Published op-ed: "Speed of Relevance in AI-enabled warfare"'}] },
    { id:'person_shanahan', type:'person', name:'Jack Shanahan (fmr.)', size:'md', tags:['operator','ex-defense','AI'], description:'Former first director of DoD Joint AI Center (JAIC). Lt. General, USAF. Now advisor to AI defense startups and VCNSA.', activity:[{date:'2026-03-13',type:'hiring',text:'Joins a16z American Dynamism as Operating Partner — defense AI'},{date:'2026-03-07',type:'research',text:'Testified: "AI integration at pace is the defining challenge of the decade"'}] },
    { id:'person_catz', type:'person', name:'Tara Chandra', size:'sm', tags:['operator','ex-government','founder'], description:'Ex-DARPA program manager (AI and autonomy). MIT PhD. Now founding a stealth defense AI startup in Arlington with DARPA funding.', activity:[{date:'2026-03-16',type:'funding',text:'DARPA Director Direct funding — $8M for stealth AI systems startup'},{date:'2026-03-09',type:'hiring',text:'First 3 hires from MIT LL and JHU APL backgrounds'}] },
  ],

  edges: [
    // ── FUNDING ──────────────────────────────────────────────────────
    { id:'e1',  source:'iqt',    target:'sievert',       type:'funding',  label:'Seed co-investor — $12M round', date:'2026-03-15' },
    { id:'e2',  source:'paladin',target:'sievert',       type:'funding',  label:'Seed co-investor — $12M round', date:'2026-03-15' },
    { id:'e3',  source:'lux',    target:'aurora_insight',type:'funding',  label:'Series A lead — $30M', date:'2026-03-13' },
    { id:'e4',  source:'avp',    target:'envision_x',   type:'funding',  label:'Seed lead — $8M', date:'2026-03-08' },
    { id:'e5',  source:'osage',  target:'envision_x',   type:'funding',  label:'Seed participant — $8M round', date:'2026-03-08' },
    { id:'e6',  source:'lux',    target:'anduril',      type:'funding',  label:'Series E participant — $1.5B round', date:'2025-12-01' },
    { id:'e7',  source:'avp',    target:'shield_ai',    type:'funding',  label:'Series F participant — $300M round', date:'2025-10-15' },
    { id:'e8',  source:'iqt',    target:'primer_ai',    type:'funding',  label:'Series B strategic investment', date:'2025-08-10' },
    { id:'e9',  source:'paladin',target:'vannevar',     type:'funding',  label:'Growth equity — $50M', date:'2025-09-20' },
    { id:'e10', source:'a16z_def',target:'hawkeye360',  type:'funding',  label:'Series C co-lead — $145M', date:'2026-03-07' },
    { id:'e11', source:'shield_cap',target:'hawkeye360',type:'funding',  label:'Series C co-lead — $145M', date:'2026-03-07' },
    { id:'e12', source:'iqt',    target:'epirus',       type:'funding',  label:'Series A co-investor — $18M', date:'2026-03-15' },
    { id:'e13', source:'lux',    target:'epirus',       type:'funding',  label:'Series A co-lead — $18M', date:'2026-03-15' },
    { id:'e14', source:'iqt',    target:'cia',          type:'funding',  label:'Strategic investment arm for IC procurement', date:'1999-01-01' },
    { id:'e15', source:'paladin',target:'rebellion_def',type:'funding',  label:'Series B participant — $80M round', date:'2024-09-01' },
    { id:'e16', source:'a16z_def',target:'anduril',     type:'funding',  label:'Series D participant — $1.5B round', date:'2025-12-01' },
    { id:'e17', source:'sq1',    target:'anduril',      type:'funding',  label:'$40M venture debt facility for R&D', date:'2026-02-01' },

    // ── CONTRACTS ─────────────────────────────────────────────────────
    { id:'e18', source:'darpa',  target:'anduril',      type:'contract', label:'$34M SBIR Phase II — autonomous swarm systems', date:'2026-02-28' },
    { id:'e19', source:'dod_diu',target:'shield_ai',    type:'contract', label:'OTA award — autonomous flight $125M', date:'2026-03-16' },
    { id:'e20', source:'dod',    target:'anduril',      type:'contract', label:'$2B integrated defense infrastructure contract', date:'2026-03-17' },
    { id:'e21', source:'nsa',    target:'sievert',      type:'contract', label:'Technical evaluation — zero trust pilot program', date:'2026-02-15' },
    { id:'e22', source:'cia',    target:'vannevar',     type:'contract', label:'IC/DIA AI fusion platform — $41M', date:'2026-03-09' },
    { id:'e23', source:'dhs',    target:'rebellion_def',type:'contract', label:'Cyber defense AI pilot — $12M', date:'2026-02-20' },
    { id:'e24', source:'darpa',  target:'jhu_apl',      type:'contract', label:'Hypersonic guidance research collaboration', date:'2026-03-17' },
    { id:'e25', source:'nga',    target:'primer_ai',    type:'contract', label:'NGA geospatial intelligence AI — $22M', date:'2026-03-13' },
    { id:'e26', source:'socom',  target:'palantir',     type:'contract', label:'SOCOM AI-enabled ISR platform — $180M', date:'2026-03-16' },
    { id:'e27', source:'afrl',   target:'rebellion_def',type:'contract', label:'Air Force AI targeting assistance — $67M IDIQ', date:'2026-03-14' },
    { id:'e28', source:'nsa',    target:'booz_allen',   type:'contract', label:'$78M cyber modernization contract', date:'2026-03-16' },
    { id:'e29', source:'dhs',    target:'booz_allen',   type:'contract', label:'DHS cyber defense modernization — $120M', date:'2026-03-11' },
    { id:'e30', source:'dod',    target:'leidos',       type:'contract', label:'Air Force IT modernization — $1.4B', date:'2026-03-15' },
    { id:'e31', source:'nra',    target:'hawkeye360',   type:'contract', label:'NRO RF geospatial intelligence contract — $55M', date:'2026-03-13' },
    { id:'e32', source:'darpa',  target:'mit_ll',       type:'contract', label:'OFFSET Phase III — autonomous swarm coordination $45M', date:'2026-03-09' },
    { id:'e33', source:'dod',    target:'palantir',     type:'contract', label:'Army AIP Phase II: AI across brigade combat teams — $400M', date:'2026-03-14' },
    { id:'e34', source:'socom',  target:'skydio',       type:'contract', label:'Army Blue UAS program — $20M initial award', date:'2026-03-16' },
    { id:'e35', source:'afrl',   target:'epirus',       type:'contract', label:'Army Leonidas HPM system fielding — $66M', date:'2026-03-10' },
    { id:'e36', source:'dtra',   target:'sievert',      type:'contract', label:'Biosurveillance AI zero-trust pilot — $14M', date:'2026-03-09' },

    // ── TALENT / OPERATOR TRANSITIONS ─────────────────────────────────
    { id:'e37', source:'dod',    target:'rebellion_def',type:'talent',   label:'Chris Lynch: DDS Director → CEO Rebellion Defense', date:'2023-01-01' },
    { id:'e38', source:'nsa',    target:'sievert',      type:'talent',   label:'Morgan Walsh: NSA TAO → Founder Sievert Labs', date:'2024-06-01' },
    { id:'e39', source:'cia',    target:'rebellion_def',type:'talent',   label:'Nicole Camarillo: NSC/DoD Cyber → CSO Rebellion', date:'2024-09-01' },
    { id:'e40', source:'anduril',target:'envision_x',  type:'talent',   label:'Ex-Anduril senior engineer co-founded EnvisionX', date:'2025-03-01' },
    { id:'e41', source:'palantir',target:'envision_x', type:'talent',   label:'Jenna Parks: Palantir FDE → Founder EnvisionX', date:'2025-01-01' },
    { id:'e42', source:'dod',    target:'shield_ai',    type:'talent',   label:'Jack Shanahan joins a16z / advises Shield AI', date:'2025-06-01' },
    { id:'e43', source:'darpa',  target:'anduril',      type:'talent',   label:'Multiple DARPA PMs → Anduril program leads', date:'2024-01-01' },
    { id:'e44', source:'booz_allen',target:'sievert',   type:'talent',   label:'2 ex-Booz Allen cyber leads join Sievert Labs', date:'2025-09-01' },

    // ── PERSON EDGES ──────────────────────────────────────────────────
    { id:'e45', source:'person_lynch',    target:'rebellion_def', type:'talent', label:'Co-founder & CEO', date:'2019-01-01' },
    { id:'e46', source:'person_camarillo',target:'rebellion_def', type:'talent', label:'Chief Strategy Officer', date:'2024-09-01' },
    { id:'e47', source:'person_gourley',  target:'primer_ai',     type:'talent', label:'Founder & CEO', date:'2016-01-01' },
    { id:'e48', source:'person_parks',    target:'envision_x',    type:'talent', label:'Founder & CEO', date:'2025-01-01' },
    { id:'e49', source:'person_walsh',    target:'sievert',       type:'talent', label:'Founder & CEO', date:'2024-06-01' },
    { id:'e50', source:'person_luckey',   target:'anduril',       type:'talent', label:'Founder & CEO', date:'2017-01-01' },
    { id:'e51', source:'person_shyu',     target:'shield_ai',     type:'talent', label:'Board of Directors — Independent Director', date:'2026-03-14' },
    { id:'e52', source:'person_shanahan', target:'a16z_def',      type:'talent', label:'Operating Partner — Defense AI', date:'2026-03-13' },
    { id:'e53', source:'person_catz',     target:'darpa',         type:'talent', label:'Former DARPA PM → Stealth startup via DARPA Director Direct', date:'2026-03-16' },

    // ── RESEARCH / COMMERCIALIZATION ──────────────────────────────────
    { id:'e54', source:'jhu_apl',  target:'vannevar',      type:'research', label:'AI targeting algorithm commercialization', date:'2025-07-15' },
    { id:'e55', source:'gmu',      target:'shield_ai',     type:'research', label:'Autonomy lab collaboration — swarm AI patents', date:'2025-11-01' },
    { id:'e56', source:'umd',      target:'sievert',       type:'research', label:'Cybersecurity Center joint R&D agreement', date:'2026-01-15' },
    { id:'e57', source:'nist',     target:'anduril',       type:'research', label:'AI safety framework co-development for autonomous systems', date:'2026-02-01' },
    { id:'e58', source:'mit_ll',   target:'epirus',        type:'research', label:'HPM systems research transfer agreement', date:'2025-05-01' },
    { id:'e59', source:'rand',     target:'dod',           type:'research', label:'AI autonomy policy advisory — SecDef strategic planning', date:'2026-03-15' },
    { id:'e60', source:'georgetown',target:'nga',          type:'research', label:'CSET geospatial AI policy briefing', date:'2026-03-10' },
    { id:'e61', source:'jhu_apl',  target:'mit_ll',        type:'research', label:'Joint quantum networking research program', date:'2025-10-01' },
    { id:'e62', source:'nist',     target:'booz_allen',    type:'research', label:'Post-quantum crypto implementation advisory', date:'2026-02-20' },
    { id:'e63', source:'umd',      target:'hawkeye360',    type:'research', label:'RF interference ML research collaboration', date:'2025-12-01' },
  ],

  liveFeed: [
    { time:'2 min ago',  type:'contract', text:'DoD awards $2B to Anduril for integrated defense infra systems', entity:'anduril' },
    { time:'8 min ago',  type:'funding',  text:'Paladin Capital closes $500M National Security Tech Fund III', entity:'paladin' },
    { time:'18 min ago', type:'hiring',   text:'Shield AI posts 20 ML engineer roles — Arlington, VA', entity:'shield_ai' },
    { time:'25 min ago', type:'contract', text:'Army awards $400M Palantir AIP Phase II across BCT units', entity:'palantir' },
    { time:'34 min ago', type:'funding',  text:'Sievert Labs closes $12M seed — IQT + Paladin lead', entity:'sievert' },
    { time:'41 min ago', type:'contract', text:'SOCOM awards Palantir $180M for AI-enabled ISR platform', entity:'socom' },
    { time:'1h ago',     type:'contract', text:'DARPA releases BAA: AI-assisted intelligence analysis — $200M ceiling', entity:'darpa' },
    { time:'1h ago',     type:'research', text:'MIT Lincoln Lab: quantum networking 500-node entanglement milestone', entity:'mit_ll' },
    { time:'2h ago',     type:'research', text:'NIST AI RMF 2.0 released — new federal AI deployment standards', entity:'nist' },
    { time:'2h ago',     type:'talent',   text:'Jack Shanahan joins a16z American Dynamism as Operating Partner', entity:'person_shanahan' },
    { time:'3h ago',     type:'hiring',   text:'Rebellion Defense recruiting ex-NSA signals intelligence — 15 roles', entity:'rebellion_def' },
    { time:'3h ago',     type:'contract', text:'HawkEye 360 closes NRO contract extension — $55M', entity:'hawkeye360' },
    { time:'4h ago',     type:'contract', text:'DIU OTA award to Shield AI — autonomous flight $125M', entity:'shield_ai' },
    { time:'5h ago',     type:'funding',  text:'Lux Capital closes $150M dual-use AI fund', entity:'lux' },
    { time:'5h ago',     type:'talent',   text:'Heidi Shyu joins Shield AI board of directors', entity:'person_shyu' },
    { time:'6h ago',     type:'research', text:'JHU APL publishes hypersonic guidance AI results with DARPA', entity:'jhu_apl' },
    { time:'7h ago',     type:'contract', text:'AFRL awards Rebellion Defense $67M IDIQ for AI targeting software', entity:'rebellion_def' },
    { time:'8h ago',     type:'contract', text:'NSA awards $78M cyber modernization contract to Booz Allen', entity:'nsa' },
    { time:'9h ago',     type:'funding',  text:'a16z American Dynamism leads $200M into autonomous undersea vehicle startup', entity:'a16z_def' },
    { time:'10h ago',    type:'hiring',   text:'DARPA posts 12 PM roles — AI and biodefense tracks', entity:'darpa' },
    { time:'11h ago',    type:'funding',  text:'EnvisionX raises $8M seed — AV8 Ventures leads', entity:'envision_x' },
    { time:'12h ago',    type:'talent',   text:'Tara Chandra (ex-DARPA) launches stealth defense AI startup in Arlington', entity:'person_catz' },
    { time:'13h ago',    type:'contract', text:'Vannevar Labs wins DIA AI fusion contract — $41M', entity:'vannevar' },
    { time:'14h ago',    type:'research', text:'UMD quantum computing center opens — $22M NIST funding', entity:'umd' },
    { time:'15h ago',    type:'hiring',   text:'Leidos opens 200 AI/ML positions in Reston, VA', entity:'leidos' },
    { time:'16h ago',    type:'contract', text:'Booz Allen wins DHS cyber defense recompete — $120M', entity:'booz_allen' },
    { time:'17h ago',    type:'research', text:'RAND: "AI Autonomy in Lethal Systems" — cited by SecDef staff', entity:'rand' },
    { time:'18h ago',    type:'hiring',   text:'CISA surge hiring: 300+ cybersecurity roles under AI taskforce', entity:'dhs' },
    { time:'20h ago',    type:'funding',  text:'Shield Capital announces $185M Fund II — AI, cyber, dual-use focus', entity:'shield_cap' },
    { time:'22h ago',    type:'contract', text:'Army Blue UAS program: Skydio wins $20M initial tranche', entity:'skydio' },
  ],

  tagColors: {
    'AI':'#3ecf8e','cyber':'#9966cc','defense':'#c94040','autonomy':'#d4a832',
    'space':'#5591c7','dual-use':'#bb653b','biotech':'#3ecf8e','quantum':'#dd6974',
    'intelligence':'#fdab43','signals':'#3ecf8e','NLP':'#5a9e3e','zero-trust':'#9966cc',
    'critical-infra':'#c94040','ISR':'#d4a832','policy':'#5591c7','operator':'#d4a832',
    'ex-defense':'#c94040','ex-nsa':'#9966cc','ex-palantir':'#3ecf8e','founder':'#5a9e3e',
    'repeat-founder':'#fdab43','ex-government':'#bb653b','advisor':'#888',
  },
};
